# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 05:07
from __future__ import unicode_literals

import CalculateProbability.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculateProbability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='Numsides',
            field=models.PositiveIntegerField(default=1, validators=[CalculateProbability.models.validate_nonzero]),
        ),
    ]
